#!/usr/bin/env node
/* eslint-disable no-console -- command-line script: its output is the report. */
/**
 * Builds the React 18 adapter (decision D6), the same way the React 19 package builds each epoch subpath:
 *
 *   dist/index.js     ONE CommonJS implementation, bundled by esbuild. It contains the adapter source, its-fine 1.2.5
 *                     and the exact react-reconciler 0.29.2 (and the scheduler 0.23 it depends on). Only `react` and
 *                     `@pixi-react-provisional/core` stay external.
 *   dist/index.mjs    a generated ESM wrapper: `import cjs from './index.js'` re-exporting each named export, so
 *                     `import` and `require` reach the same module instance.
 *   dist/**\/*.d.ts   declarations emitted by tsc; dist/index.d.mts re-exports index.d.ts.
 *
 * Like the React 19 package, the bundle keeps react-reconciler's own `process.env.NODE_ENV` switch between its
 * development and production builds. Splitting them into separate files (as the facade does) is a follow-up for both
 * adapter packages (issue 40).
 */
import { execFileSync } from 'node:child_process';
import { readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const packageDir = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(join(packageDir, 'package.json'));
const esbuild = require('esbuild');

const dist = join(packageDir, 'dist');

/** Runtime dependencies that stay external: the consumer's React and the shared core instance. */
const EXTERNAL = ['react', 'react/*', '@pixi-react-provisional/core'];

rmSync(dist, { recursive: true, force: true });

try
{
    execFileSync(process.execPath, [require.resolve('typescript/bin/tsc'), '-p', 'tsconfig.build.json'], {
        cwd: packageDir,
        stdio: 'inherit',
    });
}
catch (error)
{
    console.error('tsc (declarations) failed');
    process.exit(error.status ?? 1);
}

pruneDeclarations();

/**
 * tsc emits a declaration for every source file, including internal modules (the host config) whose declarations
 * name the bundled reconciler. Keep only the declarations reachable from the entry, so no published declaration
 * references a module the package does not ship.
 */
function pruneDeclarations()
{
    const keep = new Set();
    const pending = [join(dist, 'index.d.ts')];

    while (pending.length)
    {
        const file = pending.pop();

        if (keep.has(file))
        {
            continue;
        }

        keep.add(file);

        for (const [, specifier] of readFileSync(file, 'utf8').matchAll(/(?:from |import\()'(\.[^']+)'/g))
        {
            pending.push(resolve(dirname(file), specifier.replace(/\.js$/, '.d.ts')));
        }
    }

    const walk = (dir) => readdirSync(dir, { withFileTypes: true }).flatMap((entry) =>
        (entry.isDirectory() ? walk(join(dir, entry.name)) : [join(dir, entry.name)]));

    for (const file of walk(dist))
    {
        if (file.endsWith('.d.ts') && !keep.has(file))
        {
            rmSync(file);
        }
    }

    for (const entry of readdirSync(dist, { withFileTypes: true }))
    {
        if (entry.isDirectory() && walk(join(dist, entry.name)).length === 0)
        {
            rmSync(join(dist, entry.name), { recursive: true });
        }
    }
}

const outfile = join(dist, 'index.js');

await esbuild.build({
    entryPoints: [join(packageDir, 'src', 'index.ts')],
    outfile,
    bundle: true,
    format: 'cjs',
    platform: 'neutral',
    // its-fine 1.x ships `main` (CJS) and `module` (ESM); bundle its CommonJS build like the reconciler's.
    mainFields: ['main'],
    target: 'es2022',
    jsx: 'automatic',
    external: EXTERNAL,
    legalComments: 'inline',
    logLevel: 'warning',
});

const names = Object.keys(require(outfile)).filter((name) => name !== '__esModule' && name !== 'default').sort();

for (const name of names)
{
    if (!(/^[A-Za-z_$][\w$]*$/).test(name))
    {
        throw new Error(`Export "${name}" is not a valid ESM binding name.`);
    }
}

writeFileSync(
    join(dist, 'index.mjs'),
    [
        '// Generated by scripts/build.mjs: the ESM entry re-exports the single CJS implementation (D6).',
        'import cjs from \'./index.js\';',
        '',
        `export const {\n${names.map((name) => `    ${name},`).join('\n')}\n} = cjs;`,
        '',
    ].join('\n'),
);
writeFileSync(
    join(dist, 'index.d.mts'),
    [
        '// Generated by scripts/build.mjs: types of the single CJS implementation (D6).',
        'export * from \'./index.js\';',
        '',
    ].join('\n'),
);

console.log(`react-18: CJS bundle + ESM wrapper with ${names.length} exports`);
