#!/usr/bin/env node
/* eslint-disable no-console -- command-line script: its output is the report. */
/**
 * The generated release compatibility table (issue 40): facade version -> tested React and pixi.js ranges, plus the
 * modular package versions. Generated from design/compatibility/seed.json and release.packages.json; nothing in it is
 * written by hand. policy.mjs (and so `pnpm test:release` and the dry run) fails while the checked-in file is stale.
 *
 * Usage: node scripts/release/compat-table.mjs [--write | --check]
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { committedConfig, releaseFacts, UPSTREAM_ROW } from './compat.mjs';
import { repoRoot } from './config.mjs';

export const TABLE_FILE = 'design/release-compatibility.md';

const code = (text) => `\`${String(text).replaceAll('|', '\\|')}\``;
const versionLabel = (pkg) => `${pkg.version}${pkg.pending ? ' (Release 1, not yet published)' : ''}`;

/** The table's Markdown for the workspace at `root`. */
export function renderCompatibilityTable({ root = repoRoot } = {})
{
    const config = committedConfig(root);
    const facts = releaseFacts({ root, config });
    const { facade, pixi } = facts;
    const composed = facade.composedPackages.filter((pkg) => !['packages/core', 'packages/renderer'].includes(pkg.dir));
    const lines = [
        '# Release compatibility table',
        '',
        '<!-- Generated by `node scripts/release/compat-table.mjs --write` from design/compatibility/seed.json and release.packages.json; do not edit. -->',
        '',
        `Names are the \`${facts.namespace}\` namespace of release.packages.json (pending [issue 41](https://github.com/baseten/pixi-react/issues/41)). `
            + '**Tested** means: covered by the compatibility cells of the [#13 matrix](compatibility/cells/COMPATIBILITY.md). '
            + 'The PR-tier cells are the required check on every pull request; the nightly cells cover every Pixi 8 minor. '
            + 'This is not a support certificate: `advertisedRanges` in the manifest stays empty until the owner promotes a range '
            + '(see [release.md](release.md#what-tested-means)).',
        '',
        '## The facade',
        '',
        `| ${code(facade.publicName)} | React peer | React tested | pixi.js peer | pixi.js tested on every PR | pixi.js in the nightly cells | Builds in |`,
        '| --- | --- | --- | --- | --- | --- | --- |',
        `| ${versionLabel(facade)} | ${code(facade.peers.react)} | ${facade.reactTested.join(', ')} | ${code(facade.peers['pixi.js'])} | ${pixi.pr.join(', ')} | ${pixi.nightly.length} versions: the newest audited patch of each minor, ${pixi.nightly[0]} … ${pixi.nightly.at(-1)} | ${composed.map((pkg) => `${code(pkg.publicName)} ${pkg.version}`).join(', ')}; react-reconciler ${facade.reconciler}, its-fine ${facade.itsFine} |`,
        `| ${UPSTREAM_ROW.version} (upstream, for comparison) | ${code(UPSTREAM_ROW.react)} | - | ${code(UPSTREAM_ROW.pixi)} | - | - | ${UPSTREAM_ROW.composes} |`,
        '',
        `On a React 19 minor other than ${facade.reactMinor} the facade installs (its peer is a caret range), runs and logs one warning; `
            + `pixi.js ${pixi.excluded.join(', ')} ${pixi.excluded.length === 1 ? 'is' : 'are'} excluded from the range.`,
        '',
        '## The modular packages',
        '',
        '| Package | Version | Peers | Exact dependencies | Tested on every PR |',
        '| --- | --- | --- | --- | --- |',
    ];

    for (const pkg of facts.packages.filter((item) => !item.facade))
    {
        const peers = Object.entries(pkg.peers).filter(([name]) => !name.startsWith('@types/')).map(([name, range]) => `${name} ${code(range)}`).join(', ') || '-';
        const exact = [...pkg.internal.map((name) => `${code(name)} ${pkg.version}`), pkg.reconciler && `react-reconciler ${pkg.reconciler}`, pkg.itsFine && `its-fine ${pkg.itsFine}`].filter(Boolean).join(', ') || '-';
        let cells = pkg.dir === 'packages/pixi-8' ? 'with every React adapter row above' : 'in every cell';

        if (pkg.prCells) cells = `React ${pkg.prCells[0].react} with pixi.js ${pkg.prCells.map((cell) => cell.pixi).join(' and ')}`;

        lines.push(`| ${code(pkg.publicName)} | ${versionLabel(pkg)} | ${peers} | ${exact} | ${cells} |`);
    }
    lines.push('', `Every package releases at the facade's version (${facade.version}), and a dependency between our packages names exactly that version: install all \`${config.names.modulePrefix}*\` packages at the same version (see [release.md](release.md#lockstep-versions)).`, '');

    return lines.join('\n');
}

/** Problems if the checked-in table differs from a fresh rendering. */
export function checkCompatibilityTable({ root = repoRoot } = {})
{
    const file = join(root, TABLE_FILE);
    const expected = renderCompatibilityTable({ root });

    if (!existsSync(file)) return [`${TABLE_FILE} is missing: run node scripts/release/compat-table.mjs --write`];

    return readFileSync(file, 'utf8') === expected ? [] : [`${TABLE_FILE} is stale: run node scripts/release/compat-table.mjs --write`];
}

export function writeCompatibilityTable({ root = repoRoot } = {})
{
    writeFileSync(join(root, TABLE_FILE), renderCompatibilityTable({ root }));

    return TABLE_FILE;
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url)))
{
    if (process.argv.includes('--write')) console.log(`wrote ${writeCompatibilityTable()}`);
    else if (process.argv.includes('--check'))
    {
        const problems = checkCompatibilityTable();

        if (problems.length)
        {
            console.error(problems.join('\n'));
            process.exit(1);
        }
        console.log(`${TABLE_FILE} is current`);
    }
    else process.stdout.write(renderCompatibilityTable());
}
