#!/usr/bin/env node
/* eslint-disable no-console -- command-line script: its output is the report. */
/**
 * The docs pin generator (issue 40). One source file, apps/docs/src/release-pins.json, holds the exact `@pixi/react`,
 * `react`, `react-dom` and `pixi.js` versions every docs example uses, per docs version:
 *
 * - `current` (the docs for the facade major in development) is generated: the facade's release version and the
 *   newest React and pixi.js the release is tested with (compat.mjs, from the compatibility manifest);
 * - `frozen` holds one entry per Docusaurus version snapshot (apps/docs/versions.json). A snapshot's pins never change.
 *
 * The Sandpack editor (apps/docs/src/components/Editor) reads the file; the version literals in the current docs pages
 * and the facade README (`react@19.3.0`, `https://cdn.jsdelivr.net/npm/pixi.js@8.22.0/...`) are rewritten from it.
 * `--check` (and policy.mjs) fails when anything is stale, when an example sets its own versions, when a pinned
 * package appears without a version or as `latest`, or when the docs app's own React and pixi.js versions differ from
 * the pins. scripts/release/version.mjs regenerates the pins after `changeset version`.
 *
 * Usage: node scripts/release/docs-pins.mjs [--write | --check]
 */
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { committedConfig, releaseFacts } from './compat.mjs';
import { readJson, repoRoot } from './config.mjs';

export const PINS_FILE = 'apps/docs/src/release-pins.json';
const DOCS_APP = 'apps/docs';
/** Pages whose version literals follow the current pins: the current docs and the facade README. Snapshots are frozen. */
const PINNED_TEXT_ROOTS = ['apps/docs/docs', 'packages/react/README.md'];
/** Sources that render examples; none may carry its own version of a pinned package. */
const EXAMPLE_ROOTS = ['apps/docs/src', 'apps/docs/docs', 'apps/docs/versioned_docs'];
const EXACT = /^\d+\.\d+\.\d+$/;
/** A version ends where no prerelease tag or further digit follows (`19.3.0/`, `19.3.0.` at a sentence end). */
/** A name starts after a delimiter, never inside a longer name or after a scope (`react` inside `@pixi/react`). */
const NAME_START = '(?<![\\w@.-])(?<!@[\\w.-]+/)';
const VERSION_END = '(?![\\w-]|\\.\\d)';
const escape = (text) => text.replace(/[.+?^${}()|[\]\\/]/g, '\\$&');

function walk(root, dir, filter)
{
    const path = join(root, dir);

    if (!existsSync(path)) return [];
    if (statSync(path).isFile()) return filter(dir) ? [dir] : [];

    return readdirSync(path).flatMap((entry) => (entry === 'node_modules' || entry === 'build' || entry.startsWith('.') ? [] : walk(root, join(dir, entry), filter)));
}

const sortKeys = (object) => Object.fromEntries(Object.entries(object).sort(([a], [b]) => a.localeCompare(b)));

/** The pins file for the workspace at `root`: `current` generated, `frozen` carried over from the checked-in file. */
export function renderPins({ root = repoRoot } = {})
{
    const facts = releaseFacts({ root, config: committedConfig(root) });
    const file = join(root, PINS_FILE);
    const previous = existsSync(file) ? readJson(file) : {};

    return {
        $comment: 'Generated by `node scripts/release/docs-pins.mjs --write` (issue 40); do not edit `current`. It pins every docs example to the facade release and the newest React and pixi.js that release is tested with (design/compatibility/seed.json). `frozen` keeps the pins of each Docusaurus version snapshot (versions.json) unchanged. See design/release.md#docs-versions-and-pins.',
        current: {
            docsVersion: `${facts.facade.version.split('.')[0]}.x`,
            dependencies: sortKeys({
                [facts.facade.publicName]: facts.facade.version,
                'pixi.js': facts.pixi.newest,
                react: facts.facade.newestReact,
                'react-dom': facts.facade.newestReact,
            }),
        },
        frozen: previous.frozen ?? {},
    };
}

const serialize = (pins) => `${JSON.stringify(pins, null, 4)}\n`;

/**
 * A line that installs or imports a modular package (`@pixi-react-provisional/react-19.1`, `@pixi/react-18`,
 * `@baseten/pixi-react-pixi-8`) shows the
 * explicit composition for another React version on purpose; its versions are not the facade's pins.
 */
const MODULAR_LINE = /@[\w-]+\/(?:(?:pixi-)?react-(?:\d|core\b|renderer\b|pixi-)|core\b|renderer\b|pixi-\d)/;

/** Rewrites `name@x.y.z` for each pinned package to its pin, except on lines about the modular packages. */
export function rewriteVersions(text, dependencies)
{
    return text.split('\n').map((line) =>
    {
        if (MODULAR_LINE.test(line)) return line;
        let result = line;

        for (const [name, version] of Object.entries(dependencies))
        {
            result = result.replace(new RegExp(`${NAME_START}${escape(name)}@\\d+\\.\\d+\\.\\d+${VERSION_END}`, 'g'), `${name}@${version}`);
        }

        return result;
    }).join('\n');
}

/** Problems in one page's text: pinned packages without a version, at another version, or as `latest`. */
export function textProblems(fullText, dependencies, file)
{
    const problems = [];
    const text = fullText.split('\n').filter((line) => !MODULAR_LINE.test(line)).join('\n');

    for (const [name, version] of Object.entries(dependencies))
    {
        const pattern = escape(name);

        for (const [, found] of text.matchAll(new RegExp(`${NAME_START}${pattern}@(\\d+\\.\\d+\\.\\d+)${VERSION_END}`, 'g')))
        {
            if (found !== version) problems.push(`${file}: ${name}@${found}, the pin is ${version}`);
        }
        if (new RegExp(`(?:npm/|esm\\.sh/|unpkg\\.com/)${pattern}(?=[/"'\\s)])`).test(text)) problems.push(`${file}: a CDN URL loads ${name} without a version`);
        for (const line of text.split('\n').filter((item) => (/^\s*(?:npm (?:install|i)|pnpm add|yarn add)\s/).test(item)))
        {
            if (line.split(/\s+/).includes(name)) problems.push(`${file}: "${line.trim()}" installs ${name} without a version`);
        }
    }
    // `npm create pixi.js@latest` runs the official scaffolder, which is not one of the pinned packages.
    for (const [match] of text.matchAll(/[\w./@-]+@(?:latest|beta|next|canary)\b/g))
    {
        if (match !== 'pixi.js@latest' || !text.includes(`create ${match}`)) problems.push(`${file}: ${match} is a moving tag; pin an exact version`);
    }

    return problems;
}

/** Every pin problem of the workspace at `root`; empty when the docs are pinned and current. */
export function checkDocsPins({ root = repoRoot } = {})
{
    const problems = [];
    const expected = renderPins({ root });
    const file = join(root, PINS_FILE);
    const { dependencies } = expected.current;

    if (!existsSync(file) || readFileSync(file, 'utf8') !== serialize(expected)) problems.push(`${PINS_FILE} is stale: run node scripts/release/docs-pins.mjs --write`);
    const snapshots = readJson(join(root, DOCS_APP, 'versions.json'));

    if (JSON.stringify(Object.keys(expected.frozen).sort()) !== JSON.stringify([...snapshots].sort())) problems.push(`${PINS_FILE}: "frozen" must have exactly one entry per docs snapshot in versions.json (${snapshots.join(', ')}), found ${Object.keys(expected.frozen).join(', ') || 'none'}`);
    if (snapshots.includes(expected.current.docsVersion)) problems.push(`docs version ${expected.current.docsVersion} is both the current docs and a snapshot in versions.json`);
    for (const [label, entry] of Object.entries({ current: expected.current, ...expected.frozen }))
    {
        for (const name of ['pixi.js', 'react', 'react-dom'])
        {
            if (!EXACT.test(entry.dependencies?.[name] ?? '')) problems.push(`${PINS_FILE}: ${label} must pin ${name} to an exact version, found ${entry.dependencies?.[name]}`);
        }
        for (const [name, version] of Object.entries({ ...entry.dependencies, ...entry.extras }))
        {
            if (!EXACT.test(version)) problems.push(`${PINS_FILE}: ${label} pins ${name} to "${version}", not an exact version`);
        }
    }
    for (const page of PINNED_TEXT_ROOTS.flatMap((dir) => walk(root, dir, (path) => (/\.(mdx?|tsx?|jsx?)$/).test(path))))
    {
        problems.push(...textProblems(readFileSync(join(root, page), 'utf8'), dependencies, page));
    }
    const pinned = Object.keys(dependencies);

    for (const source of EXAMPLE_ROOTS.flatMap((dir) => walk(root, dir, (path) => (/\.(mdx?|tsx?|jsx?|json)$/).test(path))))
    {
        if (source === PINS_FILE) continue;
        const text = readFileSync(join(root, source), 'utf8');

        if ((/\bdependencies=\{/).test(text)) problems.push(`${source}: an example passes its own "dependencies"; examples take their versions from ${PINS_FILE}`);
        // Prose may show a range a reader should use (`"react": "~19.3.0"`); code may not choose a version.
        for (const name of (/\.mdx?$/).test(source) ? [] : pinned)
        {
            // A string value that is not a URL (import maps map names to versioned URLs, checked above).
            if (new RegExp(`['"]${escape(name)}['"]\\s*:\\s*['"](?!https?:)`).test(text)) problems.push(`${source}: sets a version for ${name}; examples take their versions from ${PINS_FILE}`);
        }
    }
    for (const source of EXAMPLE_ROOTS.flatMap((dir) => walk(root, dir, (path) => path.endsWith('.mdx'))))
    {
        const snapshot = source.match(/^apps\/docs\/versioned_docs\/version-([^/]+)\//)?.[1];
        const entry = snapshot ? expected.frozen[snapshot] : expected.current;

        for (const [, list] of readFileSync(join(root, source), 'utf8').matchAll(/\bextras=\{\[([^\]]*)\]\}/g))
        {
            for (const [, name] of list.matchAll(/['"]([^'"]+)['"]/g))
            {
                if (!entry?.extras?.[name]) problems.push(`${source}: example extra ${name} has no pin in ${PINS_FILE} (${snapshot ?? 'current'}.extras)`);
            }
        }
    }
    const editor = readFileSync(join(root, DOCS_APP, 'src/components/Editor/Editor.tsx'), 'utf8');

    if (!editor.includes('release-pins.json')) problems.push(`${DOCS_APP}/src/components/Editor/Editor.tsx must read its dependencies from ${PINS_FILE}`);
    const docsManifest = readJson(join(root, DOCS_APP, 'package.json'));
    const docsDeps = { ...docsManifest.dependencies, ...docsManifest.devDependencies };

    for (const name of ['react', 'react-dom', 'pixi.js'])
    {
        if (docsDeps[name] !== dependencies[name]) problems.push(`${DOCS_APP}/package.json: ${name} is ${docsDeps[name] ?? 'missing'}, the pin is ${dependencies[name]} (edit it, then run pnpm install)`);
    }

    return problems;
}

/** Writes the pins file and rewrites the version literals of the pinned pages. Returns the changed files. */
export function writeDocsPins({ root = repoRoot } = {})
{
    const pins = renderPins({ root });
    const changed = [];
    const file = join(root, PINS_FILE);

    if (!existsSync(file) || readFileSync(file, 'utf8') !== serialize(pins))
    {
        writeFileSync(file, serialize(pins));
        changed.push(PINS_FILE);
    }
    for (const page of PINNED_TEXT_ROOTS.flatMap((dir) => walk(root, dir, (path) => (/\.(mdx?|tsx?|jsx?)$/).test(path))))
    {
        const text = readFileSync(join(root, page), 'utf8');
        const next = rewriteVersions(text, pins.current.dependencies);

        if (next !== text)
        {
            writeFileSync(join(root, page), next);
            changed.push(relative(root, join(root, page)));
        }
    }

    return changed;
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url)))
{
    if (process.argv.includes('--write'))
    {
        const changed = writeDocsPins();

        console.log(changed.length ? `updated ${changed.join(', ')}` : 'docs pins already current');
    }
    else if (process.argv.includes('--check'))
    {
        const problems = checkDocsPins();

        if (problems.length)
        {
            console.error(problems.join('\n'));
            process.exit(1);
        }
        console.log('docs pins are current');
    }
    else process.stdout.write(serialize(renderPins()));
}
