import { type FeatureId, FEATURES } from './features';
import { missingCapabilities } from './runner';
import { scenarios as allScenarios } from './scenarios';

import type { ConformanceBinding } from './binding';
import type { Scenario } from './scenario';

const escapeCell = (text: string) => text.replace(/\|/g, '\\|').replace(/\n/g, ' ');

function issueLink(url: string | undefined): string
{
    const number = url?.match(/\/issues\/(\d+)$/)?.[1];

    return number ? ` ([#${number}](${url}))` : '';
}

function outcome(binding: ConformanceBinding, scenario: Scenario): string
{
    const missing = missingCapabilities(binding, scenario);

    if (missing.length)
    {
        return `not run: needs ${missing.map((id) => `\`${id}\``).join(', ')}${issueLink(scenario.pendingOn)}`;
    }

    const expected = binding.expectedFailures?.[scenario.id];

    if (expected)
    {
        return `**expected failure**: ${expected.reason}${issueLink(expected.owner)}`;
    }

    return 'pass';
}

/**
 * Renders the public-feature-to-scenario map as Markdown, with the outcome each scenario has against
 * `binding`. The committed `FEATURE-MAP.md` is this function's output for the baseline facade binding; a
 * facade unit test fails when they differ.
 */
export function renderFeatureMap(binding: ConformanceBinding, scenarios: readonly Scenario[] = allScenarios): string
{
    const lines: string[] = [
        '# Conformance feature map',
        '',
        '<!-- Generated by renderFeatureMap() in src/featureMap.ts. Do not edit by hand. -->',
        '<!-- Regenerate: pnpm --filter @pixi/react exec vitest run test/unit/featureMap -u -->',
        '',
        `Every public feature of the baseline facade and the scenarios that cover it. The last column is the outcome against the baseline binding, **${binding.id}**.`,
        '',
        '- **contract** scenarios state behaviour every binding must show.',
        '- **parity** scenarios record current upstream behaviour that decision D4 keeps in the facade. They run only for bindings that provide `parity.upstream`.',
        '- An **expected failure** is a confirmed defect of that binding. It is run, must keep failing with the recorded error, and names the issue that owns the fix.',
        '',
    ];

    const byFeature = new Map<FeatureId, Scenario[]>();

    for (const scenario of scenarios)
    {
        byFeature.set(scenario.feature, [...(byFeature.get(scenario.feature) ?? []), scenario]);
    }

    for (const [feature, title] of Object.entries(FEATURES) as Array<[FeatureId, string]>)
    {
        const covered = byFeature.get(feature) ?? [];

        lines.push(`## ${title}`, '', `Feature \`${feature}\`.`, '');

        if (!covered.length)
        {
            lines.push('No scenarios.', '');
            continue;
        }

        lines.push('| Scenario | Kind | Expected outcome | Baseline |', '| --- | --- | --- | --- |');

        for (const scenario of covered)
        {
            lines.push(`| \`${scenario.id}\` | ${scenario.kind} | ${escapeCell(scenario.expected)} | ${escapeCell(outcome(binding, scenario))} |`);
        }

        lines.push('');
    }

    const failures = scenarios.filter((scenario) => binding.expectedFailures?.[scenario.id]);
    const pending = scenarios.filter((scenario) => missingCapabilities(binding, scenario).length);

    lines.push(
        '## Summary',
        '',
        `${scenarios.length} scenarios: ${scenarios.length - failures.length - pending.length} pass, `
        + `${failures.length} expected failures, ${pending.length} not run against the baseline.`,
        '',
    );

    return `${lines.join('\n').trimEnd()}\n`;
}
