#!/usr/bin/env node
/* eslint-disable no-console -- command-line script: its output is the report. */
/**
 * Builds each React 19 epoch subpath (decisions D2 and D6):
 *
 *   dist/<epoch>/index.js     ONE CommonJS implementation, bundled by esbuild. It contains the shared adapter source,
 *                             its-fine 2.1.1, and the exact react-reconciler (and the scheduler it depends on) of that
 *                             epoch. Only `react` and `@pixi-react-provisional/core` stay external.
 *   dist/<epoch>/index.mjs    a generated ESM wrapper: `import cjs from './index.js'` re-exporting each named export,
 *                             so `import` and `require` reach the same module instance.
 *   dist/**\/*.d.ts           declarations emitted by tsc; dist/<epoch>/index.d.mts re-exports index.d.ts.
 *
 * Each subpath bundles only its own reconciler: there is no shared runtime chunk and no aggregate entry.
 */
import { execFileSync } from 'node:child_process';
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const packageDir = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(join(packageDir, 'package.json'));
const esbuild = require('esbuild');

const dist = join(packageDir, 'dist');

const EPOCHS = ['19.0', '19.1', '19.2', '19.3'];

/** Runtime dependencies that stay external: the consumer's React and the shared core instance. */
const EXTERNAL = ['react', 'react/*', '@pixi-react-provisional/core'];

rmSync(dist, { recursive: true, force: true });

try
{
    execFileSync(process.execPath, [require.resolve('typescript/bin/tsc'), '-p', 'tsconfig.build.json'], {
        cwd: packageDir,
        stdio: 'inherit',
    });
}
catch (error)
{
    console.error('tsc (declarations) failed');
    process.exit(error.status ?? 1);
}

pruneDeclarations();

/**
 * tsc emits a declaration for every source file, including internal modules (each epoch's host config) whose
 * declarations name the bundled reconciler. Keep only the declarations reachable from the subpath entries, so no
 * published declaration references a module the package does not ship.
 */
function pruneDeclarations()
{
    const keep = new Set();
    const pending = EPOCHS.map((epoch) => join(dist, epoch, 'index.d.ts'));

    while (pending.length)
    {
        const file = pending.pop();

        if (keep.has(file))
        {
            continue;
        }

        keep.add(file);

        for (const [, specifier] of readFileSync(file, 'utf8').matchAll(/(?:from |import\()'(\.[^']+)'/g))
        {
            pending.push(resolve(dirname(file), specifier.replace(/\.js$/, '.d.ts')));
        }
    }

    const walk = (dir) => readdirSync(dir, { withFileTypes: true }).flatMap((entry) =>
        (entry.isDirectory() ? walk(join(dir, entry.name)) : [join(dir, entry.name)]));

    for (const file of walk(dist))
    {
        if (file.endsWith('.d.ts') && !keep.has(file))
        {
            rmSync(file);
        }
    }
}

for (const epoch of EPOCHS)
{
    const outfile = join(dist, epoch, 'index.js');

    await esbuild.build({
        entryPoints: [join(packageDir, 'src', epoch, 'index.ts')],
        outfile,
        bundle: true,
        format: 'cjs',
        platform: 'neutral',
        mainFields: ['main'],
        target: 'es2022',
        jsx: 'automatic',
        external: EXTERNAL,
        legalComments: 'inline',
        logLevel: 'warning',
    });

    const names = Object.keys(require(outfile)).filter((name) => name !== '__esModule' && name !== 'default').sort();

    for (const name of names)
    {
        if (!(/^[A-Za-z_$][\w$]*$/).test(name))
        {
            throw new Error(`Export "${name}" of ${epoch} is not a valid ESM binding name.`);
        }
    }

    mkdirSync(dirname(outfile), { recursive: true });
    writeFileSync(
        join(dist, epoch, 'index.mjs'),
        [
            '// Generated by scripts/build.mjs: the ESM entry re-exports the single CJS implementation (D6).',
            'import cjs from \'./index.js\';',
            '',
            `export const {\n${names.map((name) => `    ${name},`).join('\n')}\n} = cjs;`,
            '',
        ].join('\n'),
    );
    writeFileSync(
        join(dist, epoch, 'index.d.mts'),
        [
            '// Generated by scripts/build.mjs: types of the single CJS implementation (D6).',
            'export * from \'./index.js\';',
            '',
        ].join('\n'),
    );

    console.log(`react-19/${epoch}: CJS bundle + ESM wrapper with ${names.length} exports`);
}
